#!/bin/bash -eu

TITLE="$1"
MESSAGE="$2"

function log () {
  echo -n "$( date ): " >> "$LOG_FILE"
  echo "$1" >> "$LOG_FILE"
}

function send_pushover () {
  log "Sending Pushover message for moved files."

  source /root/.teslaCamPushoverCredentials

  curl -F "token=$pushover_app_key" \
  -F "user=$pushover_user_key" \
  -F "title=$TITLE" \
  -F "message=$MESSAGE" \
  https://api.pushover.net/1/messages
}

function send_gotify () {
  log "Sending Gotify message for moved files."

  source /root/.teslaCamGotifySettings

  curl -X POST \
  -F "title=$TITLE" \
  -F "message=$MESSAGE" \
  -F "priority=$gotify_priority" \
  "$gotify_domain/message?token=$gotify_app_token"
}

function send_ifttt () {
  log "Sending IFTTT message for moved files."

  source /root/.teslaCamIftttSettings

  curl -X POST \
  -F "value1=$TITLE" \
  -F "value2=$MESSAGE" \
  "https://maker.ifttt.com/trigger/$ifttt_event_name/with/key/$ifttt_key"
}

function send_sns () {
  log "Sending SNS message for moved files."

  source /root/.teslaCamSNSTopicARN

  python3 /root/bin/send_sns.py -t $sns_topic_arn -s "$TITLE" -m "$MESSAGE"
}

function send_telegram () {
  log "Sending Telegram message for moved files."

  source /root/.teslaCamTelegramSettings

  curl -s -X POST \
  "https://api.telegram.org/bot${telegram_bot_token}/sendMessage" \
  --data-urlencode "chat_id=${telegram_chat_id}" \
  --data-urlencode "text=${TITLE} ${MESSAGE}"
}

[ -r "/root/.teslaCamPushoverCredentials" ] && send_pushover
[ -r "/root/.teslaCamGotifySettings" ] && send_gotify
[ -r "/root/.teslaCamIftttSettings" ] && send_ifttt
[ -r "/root/.teslaCamSNSTopicARN" ] && send_sns
[ -r "/root/.teslaCamTelegramSettings" ] && send_telegram
